language: cpp
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc-4.8.1
      script:
        - rm -rf build
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=g++-4.8 -DCMAKE_C_COMPILER=gcc-4.8 ../
        - make -j2
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - xorg-dev
            - libglu1-mesa-dev
            - g++-4.8
            - cmake
            - cmake-data
#   - os: osx
#     compiler: clang
#     script:
#       - git clone --recursive https://github.com/libigl/libigl.git ../libigl
#       - mkdir build
#       - cd build
#       - cmake ../
#       - make -j2
